spring.application.name=project1

spring.datasource.url=jdbc:sqlite:./data/room-reservation.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Schema behavior
spring.jpa.hibernate.ddl-auto=update

# Helpful logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Render port configuration
server.port=${PORT:8080}